pipeline {
    agent any
    stages {
        stage('deploy_hello_world') {
            steps {
                withKubeConfig(credentialsId: 'kube-local-test.config') {
                    sh 'kubectl get pods'
                    sh 'kubectl apply -f hello_world_job.yaml'
                }

            }
        }
    }
}